In [1]:
import ifcopenshell, ifcopenshell.geom
import numpy

f = ifcopenshell.open("F:/IfcAlignmentDriver/TestFiles/Viadotto_Acerno_ADD2_rn7jkRY.ifc")

def evaluate_curve_at(alignment, curve, distance_along):
    context = [a for a in f.by_type("IfcGeometricRepresentationContext") if a[0] == "Body"][0]
    rep = f.createIfcProductDefinitionShape(
        Representations=[
            f.createIfcShapeRepresentation(
                context,
                "Body",
                "CSG",
                Items=[
                    f.createIfcBlock(
                        f.createIfcAxis2Placement3D(f.createIfcCartesianPoint((0.0, 0.0, 0.0))),
                        0.1,
                        0.3,
                        1.0,
                    )
                ],
            )
        ]
    )
    ax = f.createIfcAxis2PlacementLinear(
        f.createIfcPointByDistanceExpression(f.createIfcLengthMeasure(distance_along), BasisCurve=curve)
    )
    pl = f.createIfcLinearPlacement(alignment.ObjectPlacement, ax)
    product = f.createIfcBuildingElementProxy(ifcopenshell.guid.new(), ObjectPlacement=pl, Representation=rep)
    shp = ifcopenshell.geom.create_shape(ifcopenshell.geom.settings(), product)
    return numpy.array(shp.transformation.matrix).reshape(4, 4).T

print(evaluate_curve_at(alignment=f[192207], curve=f[192443], distance_along=100.0))


[[-1.02623338e-01 -9.94719393e-01 -1.33444138e-03  1.76825136e+01]
 [ 9.94635307e-01 -1.02632013e-01  1.29335348e-02  9.83929978e+01]
 [-1.30021943e-02  0.00000000e+00  9.99915468e-01  5.44918337e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
