In [16]:
import ifcopenshell, ifcopenshell.geom
import numpy

#f = ifcopenshell.open("F:/IfcAlignmentDriver/TestFiles/Viadotto_Acerno_ADD2_rn7jkRY.ifc")
f = ifcopenshell.open("F:/IFC4.x-IF/IFC-files/Linear-placement-sleepers/ACCA/ACCA_sleepers-linear-placement-cant-explicit.ifc")

def evaluate_curve_at(alignment, curve, axis, distance_along):
    context = [a for a in f.by_type("IfcGeometricRepresentationContext") if a[0] == "Body"][0]
    rep = f.createIfcProductDefinitionShape(
        Representations=[
            f.createIfcShapeRepresentation(
                context,
                "Body",
                "CSG",
                Items=[
                    f.createIfcBlock(
                        f.createIfcAxis2Placement3D(f.createIfcCartesianPoint((0.0, 0.0, 0.0))),
                        0.1,
                        0.3,
                        1.0,
                    )
                ],
            )
        ]
    )
    ax = f.createIfcAxis2PlacementLinear(
        f.createIfcPointByDistanceExpression(f.createIfcLengthMeasure(distance_along), BasisCurve=curve), Axis=axis
    )
    pl = f.createIfcLinearPlacement(alignment.ObjectPlacement, ax)
    product = f.createIfcBuildingElementProxy(ifcopenshell.guid.new(), ObjectPlacement=pl, Representation=rep)
    shp = ifcopenshell.geom.create_shape(ifcopenshell.geom.settings(), product)
    return numpy.array(shp.transformation.matrix).reshape(4, 4).T

print(f[2714])
m4 = evaluate_curve_at(alignment=f[2494], curve=f[2617], axis=f[2714], distance_along=425.0)
print("Det = ",numpy.linalg.det(m4))
print(m4)

print(f[2730])
m4 = evaluate_curve_at(alignment=f[2494], curve=f[2617], axis=f[2730], distance_along=426.0)
print("Det = ",numpy.linalg.det(m4))
print(m4)


#2714=IfcDirection((-1.10764345921695E-3,-2.89782067028521E-1,9.57092015824312E-1))
Det =  1.0000000000000002
[[ 9.99941324e-01  4.16665461e-03 -9.99941449e-03  4.24999957e+02]
 [-4.16644629e-03  9.99991319e-01  4.16644681e-05 -3.47221833e-02]
 [ 9.99950129e-03  0.00000000e+00  9.99950004e-01  2.50000031e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
#2730=IfcDirection((-1.15058764822606E-3,-3.01017140692677E-1,9.53618035251677E-1))
Det =  1.0000000000000002
[[ 9.99939849e-01  4.50665141e-03 -9.99939974e-03  4.25999947e+02]
 [-4.50642610e-03  9.99989845e-01  4.50642666e-05 -3.90577258e-02]
 [ 9.99950129e-03  6.77660238e-21  9.99950004e-01  2.60000033e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
